# Generated by Django 4.2 on 2023-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_rename_wsw_mission_w3w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='w3w',
            field=models.CharField(max_length=100),
        ),
    ]
