# Generated by Django 4.2 on 2023-05-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_mission_w3w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.mission'),
        ),
    ]
