# Generated by Django 4.0.2 on 2023-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_mission_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='chapter',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
